# Generated by Django 3.2.8 on 2022-03-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='Additional_Bids_Goal_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Additional_Bids_Month_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Additional_Revenue_Month_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Avg_Project_Value_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Bids_Month_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Contractor_Segment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Converted_Date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Current_Method_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Custom_Bids_Won_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Hours_Bid_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Hours_Saved_Month_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Language_Preference_Demo_Form',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Lead_Group',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Most_Excited_to_Share_About_STACK',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Number_of_Estimators_Demo_Form',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Profit_Margin',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='ROI_Calculator_Date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Referral_Contact_Company',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Referral_Contact_Email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Referral_Contact_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Return_on_Investment_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SA_Number_of_Employees',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SA_Number_of_Users',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SC_Annual_Revenue',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SC_Industry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SC_Number_of_Employees',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SC_Number_of_Users',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='SalesLoft_Next_Step_Lead',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Trade_Market',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Trades',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Type_of_Business_Demo_Form',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='Yearly_Profit_ROI_Calc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='campaign_crm_fid',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_activity_visitor_activity_form_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_activity_visitor_activity_visitor_page_view_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='partnerInfo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
