# Generated by Django 4.0.1 on 2022-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220303_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='at_hubspot',
            field=models.TextField(blank=True, default='no', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='at_hubspot',
            field=models.TextField(blank=True, default='no', null=True),
        ),
    ]
