# Generated by Django 4.0.1 on 2022-03-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opportunity_at_hubspot_prospect_at_hubspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='at_hubspot',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='at_hubspot',
        ),
    ]
