from django.db import models


# Create your models here.
class TimeStamp(models.Model):
    """Base class containing all models common information."""

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """Define Model as abstract."""
        abstract = True

class Opportunity(TimeStamp):
    id = models.CharField(max_length=50, blank=True, default="", primary_key=True)
    name = models.TextField(blank=True, default="", null=True)
    value = models.TextField(blank=True, default="", null=True)
    probability = models.TextField(blank=True, default="", null=True)
    type = models.TextField(blank=True, default="", null=True)
    stage = models.TextField(blank=True, default="", null=True)
    status = models.TextField(blank=True, default="", null=True)
    closed_at = models.TextField(blank=True, default="", null=True)
    created_at = models.TextField(blank=True, default="", null=True)
    updated_at = models.TextField(blank=True, default="", null=True)
    campaign_id = models.TextField(blank=True, default="", null=True)
    campaign_name = models.TextField(blank=True, default="", null=True)
    prospects_prospect_id = models.TextField(blank=True, default="", null=True)
    prospects_prospect_first_name = models.TextField(blank=True, default="", null=True)
    prospects_prospect_last_name = models.TextField(blank=True, default="", null=True)
    prospects_prospect_email = models.TextField(blank=True, default="", null=True)
    prospects_prospect_company = models.TextField(blank=True, default="", null=True)
    prospects = models.TextField(blank=True, default="", null=True)
    campaign_crm_fid = models.TextField(blank=True, default="", null=True)
    at_hubspot = models.TextField(blank=True, default="no", null=True)

    def save(self, **kwargs):
        super(Opportunity, self).save()

    class Meta:
        db_table ='pardot_opportunities'

# pardot prospect
class Prospect(TimeStamp):
    id = models.CharField(max_length=50, blank=True, default="", primary_key=True)
    at_hubspot = models.TextField(blank=True, default="no", null=True)
    Yearly_Profit_ROI_Calc = models.TextField(blank=True, default="", null=True)
    grade = models.TextField(blank=True, default="", null=True)
    Time_in_App_Last_7 = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_list_email_id = models.TextField(blank=True, default="", null=True)
    assigned_to_user_created_at = models.TextField(blank=True, default="", null=True)
    Lead_Forensics = models.TextField(blank=True, default="", null=True)
    Return_on_Investment_ROI_Calc = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_form_handler_id = models.TextField(blank=True, default="", null=True)
    Working_Opps = models.TextField(blank=True, default="", null=True)
    Win_Loss_Stage = models.TextField(blank=True, default="", null=True)
    Subscription_Start_Date = models.TextField(blank=True, default="", null=True)
    SC_Number_of_Employees = models.TextField(blank=True, default="", null=True)
    Converted_Date = models.TextField(blank=True, default="", null=True)
    assigned_to_user_first_name = models.TextField(blank=True, default="", null=True)
    is_reviewed = models.TextField(blank=True, default="", null=True)
    Interest_Level = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_file_id = models.TextField(blank=True, default="", null=True)
    territory = models.TextField(blank=True, default="", null=True)
    Projects_Created_Yesterday = models.TextField(blank=True, default="", null=True)
    Referral_Contact_Company = models.TextField(blank=True, default="", null=True)
    STACK_UAG_Member = models.TextField(blank=True, default="", null=True)
    Current_Method_ROI_Calc = models.TextField(blank=True, default="", null=True)
    assigned_to_user_role = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_visitor_id = models.TextField(blank=True, default="", null=True)
    SC_Number_of_Users = models.TextField(blank=True, default="", null=True)
    MKTG_Channel = models.TextField(blank=True, default="", null=True)
    Qualification = models.TextField(blank=True, default="", null=True)
    Next_Event_Date = models.TextField(blank=True, default="", null=True)
    state = models.TextField(blank=True, default="", null=True)
    crm_lead_fid = models.TextField(blank=True, default="", null=True)
    country = models.TextField(blank=True, default="", null=True)
    Profit_Margin = models.TextField(blank=True, default="", null=True)
    STACK_Created_Date = models.TextField(blank=True, default="", null=True)
    SC_Annual_Revenue = models.TextField(blank=True, default="", null=True)
    Completed_Takeoffs_Last_30 = models.TextField(blank=True, default="", null=True)
    is_starred = models.TextField(blank=True, default="", null=True)
    On_Demand_Demo = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_campaign_id = models.TextField(blank=True, default="", null=True)
    Language_from_Pendo = models.TextField(blank=True, default="", null=True)
    department = models.TextField(blank=True, default="", null=True)
    Next_Activity_Date = models.TextField(blank=True, default="", null=True)
    IP_Country = models.TextField(blank=True, default="", null=True)
    Subscription = models.TextField(blank=True, default="", null=True)
    prospect_account_id = models.TextField(blank=True, default="", null=True)
    SalesLoft_Next_Step_Contact = models.TextField(blank=True, default="", null=True)
    Lead_Notes = models.TextField(blank=True, default="", null=True)
    Custom_Projects_Created_Last_30 = models.TextField(blank=True, default="", null=True)
    ROI_Calculator_Date = models.TextField(blank=True, default="", null=True)
    Full_Name = models.TextField(blank=True, default="", null=True)
    Sub_Segment_Assigned = models.TextField(blank=True, default="", null=True)
    Other_Reasons_UAB = models.TextField(blank=True, default="", null=True)
    Most_Excited_to_Share_About_STACK = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_updated_at = models.TextField(blank=True, default="", null=True)
    website = models.TextField(blank=True, default="", null=True)
    comments = models.TextField(blank=True, default="", null=True)
    crm_owner_fid = models.TextField(blank=True, default="", null=True)
    Qualification_Reason = models.TextField(blank=True, default="", null=True)
    Referral_Contact_Link = models.TextField(blank=True, default="", null=True)
    Type_of_Business_Demo_Form = models.TextField(blank=True, default="", null=True)
    Active_User = models.TextField(blank=True, default="", null=True)
    salutation = models.TextField(blank=True, default="", null=True)
    Contractor_Segment = models.TextField(blank=True, default="", null=True)
    email = models.TextField(blank=True, default="", null=True)
    Last_Activity_Date = models.TextField(blank=True, default="", null=True)
    assigned_to_user_updated_at = models.TextField(blank=True, default="", null=True)
    Training_Webinar_2 = models.TextField(blank=True, default="", null=True)
    Additional_Bids_Goal_ROI_Calc = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_email_id = models.TextField(blank=True, default="", null=True)
    Partner_Lead = models.TextField(blank=True, default="", null=True)
    Completed_Takeoffs_Last_7 = models.TextField(blank=True, default="", null=True)
    campaign_id = models.TextField(blank=True, default="", null=True)
    Projects_Deleted_Last_30 = models.TextField(blank=True, default="", null=True)
    StackUser_ID = models.TextField(blank=True, default="", null=True)
    employees = models.TextField(blank=True, default="", null=True)
    assigned_to_user_email = models.TextField(blank=True, default="", null=True)
    Created_Date = models.TextField(blank=True, default="", null=True)
    Web_Browser = models.TextField(blank=True, default="", null=True)
    Custom_Bids_Won_ROI_Calc = models.TextField(blank=True, default="", null=True)
    NPS_Score = models.TextField(blank=True, default="", null=True)
    campaign_crm_fid = models.TextField(blank=True, default="", null=True)
    Qualification_Notes = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_type = models.TextField(blank=True, default="", null=True)
    fax = models.TextField(blank=True, default="", null=True)
    Proposal_Opps = models.TextField(blank=True, default="", null=True)
    Lead_Group = models.TextField(blank=True, default="", null=True)
    first_name = models.TextField(blank=True, default="", null=True)
    NPS_Date = models.TextField(blank=True, default="", null=True)
    Hours_Saved_Month_ROI_Calc = models.TextField(blank=True, default="", null=True)
    SA_Number_of_Employees = models.TextField(blank=True, default="", null=True)
    years_in_business = models.TextField(blank=True, default="", null=True)
    Won_Opportunities_New_Sale = models.TextField(blank=True, default="", null=True)
    partnerInfo = models.TextField(blank=True, default="", null=True)
    city = models.TextField(blank=True, default="", null=True)
    updated_at = models.TextField(blank=True, default="", null=True)
    Current_Estimating_Method = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_visit_id = models.TextField(blank=True, default="", null=True)
    Additional_Revenue_Month_ROI_Calc = models.TextField(blank=True, default="", null=True)
    created_at = models.TextField(blank=True, default="", null=True)
    campaign_name = models.TextField(blank=True, default="", null=True)
    Win_Loss_Analysis = models.TextField(blank=True, default="", null=True)
    Stack_Leadsource = models.TextField(blank=True, default="", null=True)
    Training_Complete = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_campaign_name = models.TextField(blank=True, default="", null=True)
    Days_Active_Last_30_Days = models.TextField(blank=True, default="", null=True)
    UAB_status = models.TextField(blank=True, default="", null=True)
    Number_of_Estimators_Demo_Form = models.TextField(blank=True, default="", null=True)
    Avg_Project_Value_ROI_Calc = models.TextField(blank=True, default="", null=True)
    STACK_User_Role = models.TextField(blank=True, default="", null=True)
    Language_Preference_Demo_Form = models.TextField(blank=True, default="", null=True)
    SC_Industry = models.TextField(blank=True, default="", null=True)
    SA_Annual_Revenue = models.TextField(blank=True, default="", null=True)
    Role = models.TextField(blank=True, default="", null=True)
    Free_Subscription_Date = models.TextField(blank=True, default="", null=True)
    job_title = models.TextField(blank=True, default="", null=True)
    Projects_Deleted_Last_7 = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_email_template_id = models.TextField(blank=True, default="", null=True)
    Segment_Assigned = models.TextField(blank=True, default="", null=True)
    opted_out = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_id = models.TextField(blank=True, default="", null=True)
    Mktg_Group = models.TextField(blank=True, default="", null=True)
    last_activity_at = models.TextField(blank=True, default="", null=True)
    industry = models.TextField(blank=True, default="", null=True)
    SA_Industry = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_landing_page_id = models.TextField(blank=True, default="", null=True)
    Operating_System = models.TextField(blank=True, default="", null=True)
    Company_Annual_Revenue = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_campaign_crm_fid = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_custom_redirect_id = models.TextField(blank=True, default="", null=True)
    company = models.TextField(blank=True, default="", null=True)
    Consent_Provided = models.TextField(blank=True, default="", null=True)
    Subscription_Type = models.TextField(blank=True, default="", null=True)
    Bids_Month_ROI_Calc = models.TextField(blank=True, default="", null=True)
    SA_Number_of_Users = models.TextField(blank=True, default="", null=True)
    address_two = models.TextField(blank=True, default="", null=True)
    assigned_to_user_account = models.TextField(blank=True, default="", null=True)
    Description = models.TextField(blank=True, default="", null=True)
    assigned_to_user_job_title = models.TextField(blank=True, default="", null=True)
    crm_account_fid = models.TextField(blank=True, default="", null=True)
    Primary_Reason_For_Joining = models.TextField(blank=True, default="", null=True)
    Lofted = models.TextField(blank=True, default="", null=True)
    SalesLoft_Next_Step_Lead = models.TextField(blank=True, default="", null=True)
    password = models.TextField(blank=True, default="", null=True)
    Training_Webinar_1 = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_form_id = models.TextField(blank=True, default="", null=True)
    is_do_not_call = models.TextField(blank=True, default="", null=True)
    Last_Demonstration_Date = models.TextField(blank=True, default="", null=True)
    Contact_Owner_Calendly = models.TextField(blank=True, default="", null=True)
    Projects_Created_Last_7 = models.TextField(blank=True, default="", null=True)
    annual_revenue = models.TextField(blank=True, default="", null=True)
    phone = models.TextField(blank=True, default="", null=True)
    source = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_prospect_id = models.TextField(blank=True, default="", null=True)
    Company_Trades = models.TextField(blank=True, default="", null=True)
    address_one = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_details = models.TextField(blank=True, default="", null=True)
    Last_Session_Date = models.TextField(blank=True, default="", null=True)
    is_do_not_email = models.TextField(blank=True, default="", null=True)
    Subscription_Quantity = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_visitor_page_view_id = models.TextField(blank=True, default="", null=True)
    Projects_Deleted_Yesterday = models.TextField(blank=True, default="", null=True)
    salesforce_fid = models.TextField(blank=True, default="", null=True)
    IP_City = models.TextField(blank=True, default="", null=True)
    STACK_Company_ID = models.TextField(blank=True, default="", null=True)
    notes = models.TextField(blank=True, default="", null=True)
    Last_Visit_from_Pendo = models.TextField(blank=True, default="", null=True)
    assigned_to_user_last_name = models.TextField(blank=True, default="", null=True)
    Time_in_App_Yesterday = models.TextField(blank=True, default="", null=True)
    assigned_to_user_id = models.TextField(blank=True, default="", null=True)
    Trades = models.TextField(blank=True, default="", null=True)
    crm_url = models.TextField(blank=True, default="", null=True)
    IP_Region = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_type_name = models.TextField(blank=True, default="", null=True)
    crm_last_sync = models.TextField(blank=True, default="", null=True)
    MKTG_Source = models.TextField(blank=True, default="", null=True)
    Referral_Link = models.TextField(blank=True, default="", null=True)
    Hours_Bid_ROI_Calc = models.TextField(blank=True, default="", null=True)
    Additional_Bids_Month_ROI_Calc = models.TextField(blank=True, default="", null=True)
    Training_1 = models.TextField(blank=True, default="", null=True)
    score = models.TextField(blank=True, default="", null=True)
    last_name = models.TextField(blank=True, default="", null=True)
    Minutes_on_Site_Last_30_Days = models.TextField(blank=True, default="", null=True)
    Demo_Completed = models.TextField(blank=True, default="", null=True)
    Qualification_Sub_Status = models.TextField(blank=True, default="", null=True)
    Subscription_End_Date = models.TextField(blank=True, default="", null=True)
    Subscription_Status = models.TextField(blank=True, default="", null=True)
    Referral_Contact_Name = models.TextField(blank=True, default="", null=True)
    last_activity_visitor_activity_created_at = models.TextField(blank=True, default="", null=True)
    Lost_Opportunities_New_Sale = models.TextField(blank=True, default="", null=True)
    recent_interaction = models.TextField(blank=True, default="", null=True)
    Trade_Market = models.TextField(blank=True, default="", null=True)
    Referral_Contact_Email = models.TextField(blank=True, default="", null=True)
    Sub_Segment_Group = models.TextField(blank=True, default="", null=True)
    zip = models.TextField(blank=True, default="", null=True)
    crm_contact_fid = models.TextField(blank=True, default="", null=True)

    def save(self, **kwargs):
        super(Prospect, self).save()

    class Meta:
        db_table ='pardot_prospects'

